In [1]:
import pandas as pd

In [37]:
df=pd.read_csv('e://myfiles//population_india_census2011.csv')

In [38]:
df.head(2)

,Sno,State / Union Territory,Population,Rural population,Urban population,Area,Density,Gender Ratio
0,1,Uttar Pradesh,199812341,155317278,44495063,"240,928 km2 (93,023 sq mi)","828/km2 (2,140/sq mi)",912
1,2,Maharashtra,112374333,61556074,50818259,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929

In [39]:
df.columns

Index(['Sno', 'State / Union Territory', 'Population', 'Rural population',
       'Urban population', 'Area', 'Density', 'Gender Ratio'],
      dtype='object')

In [40]:
c_=df.columns.values

In [41]:
c_[1]

'State / Union Territory'

In [42]:
c_[1]='Region'

In [43]:
df.head(2)

,Sno,Region,Population,Rural population,Urban population,Area,Density,Gender Ratio
0,1,Uttar Pradesh,199812341,155317278,44495063,"240,928 km2 (93,023 sq mi)","828/km2 (2,140/sq mi)",912
1,2,Maharashtra,112374333,61556074,50818259,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929

In [44]:
df.shape

(36, 8)

# total population

In [45]:
df['Population'].sum()

1210568111

In [46]:
df['Rural population'].sum()

833521087

In [47]:
df['Urban population'].sum()

377047024

In [48]:
df.columns.value_counts

<bound method IndexOpsMixin.value_counts of Index(['Sno', 'Region', 'Population', 'Rural population', 'Urban population',
       'Area', 'Density', 'Gender Ratio'],
      dtype='object')>

In [49]:
df_c=df.groupby('Area')['Population','Rural population','Urban population']

C:\Users\Mumin\New folder\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

In [50]:
df.head()

,Sno,Region,Population,Rural population,Urban population,Area,Density,Gender Ratio
0,1,Uttar Pradesh,199812341,155317278,44495063,"240,928 km2 (93,023 sq mi)","828/km2 (2,140/sq mi)",912
1,2,Maharashtra,112374333,61556074,50818259,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929
2,3,Bihar,104099452,92341436,11758016,"94,163 km2 (36,357 sq mi)","1,102/km2 (2,850/sq mi)",918
3,4,West Bengal,91276115,62183113,29093002,"88,752 km2 (34,267 sq mi)","1,029/km2 (2,670/sq mi)",953
4,5,Madhya Pradesh,72626809,52557404,20069405,"308,245 km2 (119,014 sq mi)",236/km2 (610/sq mi),931

In [51]:
df['Region']

KeyError: 'Region'

In [52]:
df.iloc[23]

Sno                                       24
Region                              Nagaland
Population                           1978502
Rural population                     1407536
Urban population                      570966
Area                16,579 km2 (6,401 sq mi)
Density                  119/km2 (310/sq mi)
Gender Ratio                             931
Name: 23, dtype: object

In [53]:
df.Region

AttributeError: 'DataFrame' object has no attribute 'Region'

In [54]:
df.to_csv('e://myfiles//ppp.csv')

In [55]:
pd.read_csv('e://myfiles//ppp.csv')

,Unnamed: 0,Sno,Region,Population,Rural population,Urban population,Area,Density,Gender Ratio
0,0,1,Uttar Pradesh,199812341,155317278,44495063,"240,928 km2 (93,023 sq mi)","828/km2 (2,140/sq mi)",912
1,1,2,Maharashtra,112374333,61556074,50818259,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929
2,2,3,Bihar,104099452,92341436,11758016,"94,163 km2 (36,357 sq mi)","1,102/km2 (2,850/sq mi)",918
3,3,4,West Bengal,91276115,62183113,29093002,"88,752 km2 (34,267 sq mi)","1,029/km2 (2,670/sq mi)",953
4,4,5,Madhya Pradesh,72626809,52557404,20069405,"308,245 km2 (119,014 sq mi)",236/km2 (610/sq mi),931
5,5,6,Tamil Nadu,72147030,37229590,34917440,"130,058 km2 (50,216 sq mi)","555/km2 (1,440/sq mi)",996
6,6,7,Rajasthan,68548437,51500352,17048085,"342,239 km2 (132,139 sq mi)",201/km2 (520/sq mi),928
7,7,8,Karnataka,61095297,37469335,23625962,"191,791 km2 (74,051 sq mi)",319/km2 (830/sq mi),973
8,8,9,Gujarat,60439692,34694609,25745083,"196,024 km2 (75,685 sq mi)",308/km2 (800/sq mi),919
9,9,10,Andhra Pradesh,49577103,34966693,14610410,"162,968 km2 (62,922 sq mi)",303/km2 (780/sq mi),993
10,10,11,Odisha,41974218,34970562,7003656,"155,707 km2 (60,119 sq mi)",269/km2 (700/sq mi),979
11,11,12,Telengana,35003674,21395009,13608665,"112,077 km2 (43,273 sq mi)",312/km2 (810/sq mi),988
12,12,13,Kerala,33406061,17471135,15934926,"38,863 km2 (15,005 sq mi)","859/km2 (2,220/sq mi)",1084
13,13,14,Jharkhand,32988134,25055073,7933061,"79,714 km2 (30,778 sq mi)","414/km2 (1,070/sq mi)",948
14,14,15,Assam,31205576,26807034,4398542,"78,438 km2 (30,285 sq mi)","397/km2 (1,030/sq mi)",954
15,15,16,Punjab,27743338,17344192,10399146,"50,362 km2 (19,445 sq mi)","550/km2 (1,400/sq mi)",895
16,16,17,Chhattisgarh,25545198,19607961,5937237,"135,191 km2 (52,198 sq mi)",189/km2 (490/sq mi),991
17,17,18,Haryana,25351462,16509359,8842103,"44,212 km2 (17,070 sq mi)","573/km2 (1,480/sq mi)",879
18,18,19,Uttarakhand,10086292,7036954,3049338,"53,483 km2 (20,650 sq mi)",189/km2 (490/sq mi),963
19,19,20,Himachal Pradesh,6864602,6176050,688552,"55,673 km2 (21,495 sq mi)",123/km2 (320/sq mi),972
20,20,21,Tripura,3673917,2712464,961453,"10,486 km2 (4,049 sq mi)",350/km2 (910/sq mi),960
21,21,22,Meghalaya,2966889,2371439,595450,"22,429 km2 (8,660 sq mi)",132/km2 (340/sq mi),989
22,22,23,Manipur,2570390,1793875,776515,"22,327 km2 (8,621 sq mi)",122/km2 (320/sq mi),992
23,23,24,Nagaland,1978502,1407536,570966,"16,579 km2 (6,401 sq mi)",119/km2 (310/sq mi),931
24,24,25,Goa,1458545,551731,906814,"3,702 km2 (1,429 sq mi)","394/km2 (1,020/sq mi)",973
25,25,26,Arunachal Pradesh,1383727,1066358,317369,"83,743 km2 (32,333 sq mi)",17/km2 (44/sq mi),938
26,26,27,Mizoram,1097206,525435,571771,"21,081 km2 (8,139 sq mi)",52/km2 (130/sq mi),976
27,27,28,Sikkim,610577,456999,153578,"7,096 km2 (2,740 sq mi)",86/km2 (220/sq mi),890
28,28,29,Delhi,16787941,419042,16368899,"1,484 km2 (573 sq mi)","11,297/km2 (29,260/sq mi)",868
29,29,30,Jammu and Kashmir,12267032,9064220,3202812,"125,535 km2 (48,469 sq mi)",98/km2 (250/sq mi),890
30,30,31,Puducherry,1247953,395200,852753,479 km2 (185 sq mi),"2,598/km2 (6,730/sq mi)",1037
31,31,32,Chandigarh,1055450,28991,1026459,114 km2 (44 sq mi),"9,252/km2 (23,960/sq mi)",818
32,32,33,Dadra and Nagar Haveli and Daman and Diu,585764,243510,342254,603 km2 (233 sq mi),"970/km2 (2,500/sq mi)",711
33,33,34,Andaman and Nicobar Islands,380581,237093,143488,"8,249 km2 (3,185 sq mi)",46/km2 (120/sq mi),876
34,34,35,Ladakh,274000,43840,230160,"96,701 km2 (37,336 sq mi)",2.8/km2 (7.3/sq mi),853
35,35,36,Lakshadweep,64473,14141,50332,32 km2 (12 sq mi),"2,013/km2 (5,210/sq mi)",946